services:
  - type: web
    name: planning-poker-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5555
    healthCheckPath: /health 