services:
  - type: web
    name: planning-poker-backend
    runtime: node
    plan: free
    buildCommand: cd shared && npm ci && npm run build && cd ../backend && npm ci && mkdir -p node_modules/@shared && ls -la ../shared/dist/ && cp -r ../shared/dist/* node_modules/@shared/ && ls -la node_modules/@shared/ && npm run build:prod
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://planning-poker-frontend-ac8h.onrender.com
    
  - type: web
    name: planning-poker-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: cd ../shared && npm ci --ignore-scripts && npm run build && cd ../frontend && npm ci --ignore-scripts && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://planning-poker-backend-ac8h.onrender.com
      - key: VITE_SOCKET_URL
        value: https://planning-poker-backend-ac8h.onrender.com