services:
  - type: web
    name: planning-poker-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm ci && npm run build:prod
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://planning-poker-frontend.onrender.com
    
  - type: web
    name: planning-poker-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci --ignore-scripts && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://planning-poker-juwg.onrender.com
      - key: VITE_SOCKET_URL
        value: https://planning-poker-juwg.onrender.com