name: Auto Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Render Deploy
      run: |
        echo "Render will automatically deploy from GitHub"
        echo "Backend: https://planning-poker-backend.onrender.com"
        echo "Frontend: https://planning-poker-frontend.onrender.com"